apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/cilium-1.12.0.tgz
  valuesContent: |-
    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDR: "10.42.0.0/16"
        clusterPoolIPv4MaskSize: 24