name: Build Release for arm64
on:
  push:
    branches:
      - arm64-builder
jobs:
  build:
    name: Build & Release
    runs-on: ['self-hosted','ARM64','ubuntu-08']
    strategy:
      matrix:
        include:
          - goarch: arm64
            goos: linux
    env:
      RELEASE_TAG: ${{secrets.RELEASE_TAG}}
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: check depends
      run: sudo apt-get install -y libseccomp-dev
    - name: generate resources
      run: mkdir -p {build/data,build/static} && make generate
    - name: package bin
      run: SKIP_VALIDATE=true make
    - name: package airgap image
      run: make package-airgap
    - name: sha256sum artifacts
      run: sha256sum dist/artifacts/k8e dist/artifacts/k8e-airgap-images.tar.gz >> k8e-hashes.txt
    - name: Uploading assets...
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/artifacts/k8e
          dist/artifacts/k8e-airgap-images.tar.gz
          dist/artifacts/k8e-images.txt
          k8e-hashes.txt